code/src/work_01_Session/Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Mvc;
using work_01_Session.Models;

namespace work_01_Session.Controllers
{
    public class ShoppingController : Controller
    {
        private readonly ECommerceDbContext dbContext = null;
        public ShoppingController(ECommerceDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            ViewBag.msg = TempData["msg"];
            return View(dbContext.Products.ToList());
        }
        //public IActionResult Index()
        //{
        //    ViewBag.msg = TempData["msg"];
        //    var dbContext = new ECommerceDbContext();
        //    ViewBag.DbContext = dbContext;
        //    return View(dbContext.Products.ToList());
        //}

        public IActionResult AddToCart(int pid, double qty)
        {
            bool itemFound = false;
            string msg = "";

            if (pid > 0 && qty > 0)
            {
                var prod = dbContext.Products.FirstOrDefault(p => p.Id == pid);
                if (prod != null)
                {
                    if (qty > prod.Quantity)
                    {
                        msg = "You can't buy more than our current stock.";
                    }
                    else
                    {
                        List<Product> items = new List<Product>();
                        var xitems = HttpContext.Session.GetObject<List<Product>>("cart");
                        if (xitems != null)
                        {
                            foreach (var item in xitems)
                            {
                                if (pid == item.Id)
                                {
                                    item.Quantity += qty;
                                    itemFound = true;
                                    msg = "Item already added, new qty is added!!!";
                                }
                                items.Add(item);
                            }
                            if (!itemFound)
                            {
                                prod.Quantity = qty;
                                items.Add(prod);
                                msg = "New Item is added with existing items!!!";
                            }
                            HttpContext.Session.SetObject<List<Product>>("cart", items);
                        }
                        else
                        {
                            prod.Quantity = qty;
                            items.Add(prod);
                            HttpContext.Session.SetObject<List<Product>>("cart", items);
                            msg = "Item is added to empty cart!!";
                        }
                    }
                }
                else
                {
                    msg = "Item not found!!!";
                }
            }
            else
            {
                msg = "Item Id or qty could not be zero!!!";
            }

            TempData["msg"] = msg;
            return RedirectToAction("Index");
        }
        //public IActionResult ShowCart()
        //{
        //    List<Product> items = HttpContext.Session.GetObject<List<Product>>("cart");
        //    if (items != null && items.Count != 0)
        //    {
        //        return View(items.ToList());
        //    }
        //    else
        //    {
        //        items = new List<Product>();
        //        return View();
        //    }
        //}
        public IActionResult ShowCart()
        {
            List<Product> items = HttpContext.Session.GetObject<List<Product>>("cart");
            List<Product> updatedItems = new List<Product>();

            if (items != null)
            {
                foreach (var item in items)
                {
                    var prod = dbContext.Products.FirstOrDefault(p => p.Id == item.Id);
                    if (prod != null)
                    {
                        updatedItems.Add(item);
                    }
                }
            }

            if (updatedItems.Count != 0)
            {
                return View(updatedItems);
            }
            else
            {
                return View();
            }
        }

        public IActionResult RemoveFromCart(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            List<Product> productList = HttpContext.Session.GetObject<List<Product>>("cart");
            var removeItem = productList.FirstOrDefault(x => x.Id == id);
            productList.Remove(removeItem);
            HttpContext.Session.SetObject<List<Product>>("cart", productList);
            return RedirectToAction(nameof(ShowCart));
        }
        //public IActionResult RemoveFromCart(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    List<Product> productList = HttpContext.Session.GetObject<List<Product>>("cart");
        //    var removeItem = productList.FirstOrDefault(x => x.Id == id);
        //    if (removeItem != null)
        //    {
        //        productList.Remove(removeItem);
        //        HttpContext.Session.SetObject<List<Product>>("cart", productList);
        //    }

        //    return RedirectToAction(nameof(ShowCart));
        //}

        public IActionResult CheckOut()
        {
            var us = HttpContext.Session.GetString("un");
            var id = HttpContext.Session.GetString("id");

            if(us != null)
            {
                return RedirectToAction(nameof(ConfirmOrder));
            }
            else
            {
                return View(nameof(Login));
            }
        }
        public IActionResult ConfirmOrder()
        {
            return View();
        }
        public IActionResult Login(AppUser appUser)
        {
            var userName = dbContext.AppUsers.FirstOrDefault(x => x.UserName == appUser.UserName);
            var password = dbContext.AppUsers.FirstOrDefault(x => x.Password == appUser.Password);
            if (userName != null && password != null)
            {
                HttpContext.Session.SetString("un", appUser.UserName);
                HttpContext.Session.SetString("id", appUser.Password);
                return RedirectToAction(nameof(ConfirmOrder));

            }
            else
            {
                TempData["wrongInfo"] = "Wrong Information!!";
                return View(appUser);
            }
        }
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp([Bind("UserName, Password")] AppUser appUser)
        {
            string msg = "";
            if (ModelState.IsValid)
            {
                appUser.Role = 1;
                appUser.IsActive = true;
                var checkUserName = dbContext.AppUsers.FirstOrDefault(x => x.UserName.ToLower() == appUser.UserName.ToLower());
                if(checkUserName != null)
                {
                    TempData["signUp"] = "Username already exist!!";
                    return View(appUser);
                }
                dbContext.AppUsers.Add(appUser);
                await dbContext.SaveChangesAsync();
                HttpContext.Session.SetString("un", appUser.UserName);
                HttpContext.Session.SetString("id", appUser.Password);

                appUser.UserName = null;
                appUser.Password = null;
                TempData["signUp"] = "User registration successfull!!!";
                return RedirectToAction(nameof(Login));

            }
            else
            {
                msg = "Invalid Username or password!!!";
                return View(appUser);
            }
        }
    }
}

code/src/work_01_Session/Views/Shopping/ConfirmOrder.cshtml
@{
    ViewData["Title"] = "ConfirmOrder";
}

<h1 class="display-4 bg-success text-light text-center">We received your order</h1>
<br />
<h2 class="bg-warning text-center p-3 text-light">You have successfully created the Order।  Please wait till product is delivered। Thanks for ordering </h2>

code/src/work_01_Session/Views/Shopping/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
}
@using work_01_Session.Models
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor _httpContextAccessor

@{
    List<Product> productList = _httpContextAccessor.HttpContext.Session.GetObject<List<Product>>("cart");
    double count = 0;
    if (productList != null)
    {
        foreach (var item in productList)
        {
            count += item.Quantity;
        }
    }
    else
    {
        productList = new List<Product>();
    }
}
@*@{
    var dbContext = (ECommerceDbContext)ViewBag.DbContext;
    List<Product> productList = _httpContextAccessor.HttpContext.Session.GetObject<List<Product>>("cart");
    double count = 0;
    if (productList != null)
    {
        foreach (var item in productList)
        {
            var product = dbContext.Products.FirstOrDefault(p => p.Id == item.Id);
            if (product != null)
            {
                count += item.Quantity;
            }
        }
    }
    else
    {
        productList = new List<Product>();
    }
}*@



<div class="row">
    <div class="display-4 class= col-10 alert alert-secondary">Shopping Recommendations....</div>
    <div class="col-2 justify-content-end mb-10">
        <a asp-action="ShowCart" asp-controller="Shopping" style="text-decoration:none; position: relative; display: inline-block;">
            <img src="~/images/cart.jpg" width="90" class="img-fluid" alt="Cart" />
            <span style="position: absolute; top: 7px; right: 7px; background-color: white; color: red; font-size: 16px; padding: 2px 8px; border-radius: 50%;">@count</span>
        </a>
    </div>

</div>
<div class="row mb-2">
    <div class="col-10">
        @if (TempData["msg"] != null)
        {
            <h2 class="alert alert-info text-center">@TempData["msg"]</h2>
        }
    </div>
</div>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-sm-6 mb-4">
            <div class="card border-secondary border-2">
                <div class="product-image">
                    <img src="~/Images/@item.Image" alt="Product Image" />
                </div>
                <div class="card-body">
                    <h4 class="card-title text-center text-primary text-capitalize text-decoration-underline">@Html.DisplayFor(x => item.Name)</h4>
                    <p class="card-text"><strong>Unit: </strong>@Html.DisplayFor(x => item.Unit)</p>
                    @*<p class="card-text"><strong>Price: </strong>@Html.DisplayFor(x => item.Price)</p>*@
                    <p class="card-text"><strong>Current Stock: </strong>@item.Quantity</p>
                    <p class="card-text">
                        <strong>Price: </strong>
                        <span class="text-decoration-line-through">@Html.DisplayFor(x => item.Price)</span>
                        @if (item.Price > 0)
                        {
                            double discount = item.Price * 0.07;
                            double discountedPrice = item.Price - discount;
                            <br />
                            <strong>Discounted Price: </strong>
                            <span class="text-success font-weight-bold">@discountedPrice</span>
                        }
                    </p>


                    <form asp-action="AddToCart" asp-controller="Shopping" method="post">
                        <input type="hidden" name="pid" value="@item.Id" />
                        @if (item.Quantity <= 0)
                        {
                            <span class="badge bg-danger text-white text-sm" style="margin-right: 5px;">Sold Out</span>
                            <button type="submit" class="btn btn-outline-success btn-sm" disabled>Add To Cart</button>
                        }
                        else
                        {
                            <div style="display: flex; align-items: center;">
                                <input type="number" name="qty" min="1" max="500" class="form-control form-control-sm border-2 border-danger" style="width: 70px;" value="1" />
                                <button type="submit" class="btn btn-success btn-sm" style="margin-left: 7px;">Add To Cart</button>
                            </div>
                        }
                    </form>
                </div>
            </div>
        </div>
    }
</div>
<style>
    .product-image {
        height: 150px;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 5px;
    }

        .product-image img {
            height: 100%;
            width: 100%;
            object-fit: cover;
        }
</style>






@*<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
            <div class="card border-secondary border-2">
                <div class="product-image">
                    <span><img src="~/Images/@item.Image" alt="Product Image" /></span>
                </div>
                <div class="card-body">
                    <h4 class="card-title text-center text-primary text-capitalize text-decoration-underline">@Html.DisplayFor(x => item.Name)</h4>
                    <p class="card-text"><strong>Unit: </strong>@Html.DisplayFor(x => item.Unit)</p>
                    <p class="card-text"><strong>Price: </strong>@Html.DisplayFor(x => item.Price)</p>
                    <p class="card-text"><strong>Current Stock: </strong>@item.Quantity</p>
                    <form asp-action="AddToCart" asp-controller="Shopping" method="post">
                        <input type="hidden" name="pid" value="@item.Id" />
                        @if (item.Quantity <= 0)
                        {
                            <span class="badge bg-danger text-white text-sm" style="margin-right: 5px;">Sold Out</span>
                            <button type="submit" class="btn btn-outline-success btn-sm" disabled>Add To Cart</button>
                        }
                        else
                        {
                            <div style="display: flex; align-items: center;">
                                <input type="number" name="qty" min="1" max="500" class="form-control form-control-sm border-2 border-danger" style="width: 60px;" value="1" />
                                <button type="submit" class="btn btn-success btn-sm" style="margin-left: 5px;">Add To Cart</button>
                            </div>

                        }
                    </form>
                </div>
            </div>
        </div>
    }
</div>
<style>
    .product-image {
        display: flex;
        align-items: center;
        justify-content: center;
        border: 1px solid #000;
/*        height: 30px;
        width: 35px;*/
    }

        .product-image span {
            font-weight: bold;
        }*@

code/src/work_01_Session/Views/Shopping/Login.cshtml
@model work_01_Session.Models.AppUser
@{
    ViewData["Title"] = "Login";
}

<h1 class="display-4">Login</h1>
<div class="row">
    <div class="col-6">
        <form asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mb-2">
                <label asp-for="UserName" class="col-form-label"></label>
                <input asp-for="UserName" class="form-control"/>
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="row mb-2">
                <label asp-for="Password" class="col-form-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="row mb-2">
                <input type="submit" value="Login" class="btn btn-success btn-sm"/>
            </div>
        </form>
    </div>
    <div class="col-6">
        @if (TempData["wrongInfo"] != null)
        {
            <h2 class="alert alert-success p-3 text-center">@TempData["wrongInfo"]</h2>
        }
    </div>
</div>
<div>
    <a asp-action="SignUp" asp-controller="Shopping" class="btn btn-primary">SignUp</a>
    <a asp-action="Index">Back to List</a>
</div>

code/src/work_01_Session/Views/Shopping/ShowCart.cshtml
@model IEnumerable<Product>
@using work_01_Session.Models
@{
    ViewData["Title"] = "ShowCart";
}


@*@{
    double subtotal = 1;
    double total = 0;
}
<h1 class="display-4">Show Cart</h1>

<div class="border border-info p-2 mb-2">
    @if (Model != null)
    {

        <table class="table table-responsive-sm table-striped table-sm">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(x=>x.Name)</th>
                    <th>@Html.DisplayNameFor(x=>x.Unit)</th>
                    <th>@Html.DisplayNameFor(x=>x.Price)</th>
                    <th>@Html.DisplayNameFor(x=>x.Quantity)</th>
                    <th>Total Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x=>item.Name)</td>
                        <td>@Html.DisplayFor(x=>item.Unit)</td>
                        <td>@Html.DisplayFor(x=>item.Price)</td>
                        <td>@Html.DisplayFor(x=>item.Quantity)</td>
                        <td>
                            @{
                                subtotal = item.Quantity * item.Price;
                                total += subtotal;
                            }
                            @subtotal
                        </td>
                        <td width="70px">
                            <a asp-action="RemoveFromCart" asp-controller="Shopping" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="fw-bold">Total Price</td>
                    <td colspan="2">
                        @total
                        <strike style="color: red;">@(total * 0.95)</strike>
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="fw-bold">5% Discounted Price</td>
                    <td colspan="2">@total * 0.95</td>
                </tr>
            </tfoot>
        </table>
    }
    else
    {
        <div class="row">
            <div class="col-10">
                <h2 class="text-center text-danger">Item Not Found!!</h2>
            </div>
            <div class="col-2">
                <a asp-action="Index" asp-controller="Shopping" class="btn btn-primary">Back to Shopping</a>
            </div>
        </div>
    }
</div>*@

@{
    double subtotal = 1;
    double total = 0;
}

<h1 class="display-4">Show Cart</h1>

<div class="border border-info p-2 mb-2">
    @if (Model != null)
    {
@*        double subtotal = 1;
        double total = 0;*@

        <table class="table table-responsive-sm table-striped table-sm">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(x => x.Name)</th>
                    <th>@Html.DisplayNameFor(x => x.Unit)</th>
                    <th>@Html.DisplayNameFor(x => x.Price)</th>
                    <th>@Html.DisplayNameFor(x => x.Quantity)</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => item.Name)</td>
                        <td>@Html.DisplayFor(x => item.Unit)</td>
                        <td>@Html.DisplayFor(x => item.Price)</td>
                        <td>@Html.DisplayFor(x => item.Quantity)</td>
                        <td>
                            @{
                                subtotal = item.Quantity * item.Price;
                                total += subtotal;
                            }
                            <span >@subtotal</span>
                        </td>
                        <td width="70px">
                            <a asp-action="RemoveFromCart" asp-controller="Shopping" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="fw-bold">Total Price</td>
                    <td colspan="2">
                        <strike style="color: red;">@total</strike>
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="fw-bold">5% Discounted Price</td>
                    <td colspan="2">
                        <span style="color: green;" class="text-success">@((total * 0.95).ToString("0.00"))</span>
                    </td>
                </tr>
            </tfoot>
        </table>
    }
    else
    {
        <div class="row">
            <div class="col-10">
                <h2 class="text-center text-danger">Item Not Found!!</h2>
            </div>
            <div class="col-2">
                <a asp-action="Index" asp-controller="Shopping" class="btn btn-primary">Back to Shopping</a>
            </div>
        </div>
    }
</div>




<div class="row">
    <div class="col-10">
        <a asp-action="Index" asp-controller="Shopping" class="btn btn-primary">Continue to Shopping</a>
    </div>
    <div class="col-2 d-flex justify-content-end">
        @if (total == 0)
        {
            <button disabled="disabled" style="cursor:not-allowed" class="btn btn-success">Checkout Now</button>
        }
        else
        {
            <a asp-action="CheckOut" asp-controller="Shopping" class="btn btn-success">Checkout Now</a>
        }
    </div>
</div>

code/src/work_01_Session/Views/Shopping/SignUp.cshtml
@model AppUser
@{
    ViewData["Title"] = "SignUp";
}
<h1 class="display-4">SignUp</h1>
<div class="row">
    <div class="col-6">
        <form asp-action="SignUp" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mb-2">
                <label asp-for="UserName" class="col-form-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="row mb-2">
                <label asp-for="Password" class="col-form-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="row mb-2">
                <input type="submit" value="Register" class="btn btn-success btn-sm" />
            </div>
        </form>
    </div>
    <div class="col-6">
        @if (TempData["signUp"] != null)
        {
            <h2 class="alert alert-success p-3 text-center">@TempData["signUp"]</h2>
        }
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>